#!/usr/bin/env python3
"""Maintain the perf/optimization_status.md notebooks.

Subcommands:

  migrate <file> --backend <name> [--dry-run]
      One-off normalization of a notebook to the canonical form: append-only,
      oldest-first, every entry heading `## YYYY-MM-DD: <title> — VERDICT`,
      with a generated index after the preamble. Driven by the embedded
      MIGRATION_MANIFEST; fails closed on any undated heading the manifest
      does not list, and refuses to write unless the integrity gates pass
      (body-line multiset equality, heading bijection, idempotency).

  index <file> [--check]
      Regenerate (or with --check, verify) the generated index block.

  check <file> [<file> ...]
      Lint: canonical heading format, verdict vocabulary, oldest-first
      ordering, index present and fresh.

The verdict vocabulary is LANDED, KEPT, REJECTED, CANDIDATE, DEFERRED,
INCONCLUSIVE, MIXED, RECORDED (plus UNLABELED for pre-migration entries whose
verdict could not be inferred without guessing). Legacy tokens that already
appeared in headings are preserved verbatim and whitelisted, never normalized.
"""

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

VOCAB = {
    "LANDED", "KEPT", "REJECTED", "CANDIDATE", "DEFERRED",
    "INCONCLUSIVE", "MIXED", "RECORDED", "UNLABELED",
}
LEGACY = {
    "SOLVED", "VALIDATED", "FEASIBILITY", "PARTIAL", "SUPERSEDED", "BLOCKED",
    "CLOSED", "BASELINED", "FIXED", "RESOLVED", "WIP", "KEEP", "REJECT",
}
KNOWN = VOCAB | LEGACY

# H2 headings that are preamble furniture, not entries. They stay at H2 level
# at the top of the file, before the index and the first dated entry.
PREAMBLE_HEADINGS = {"Entry Template", "Required Entry Fields"}

INDEX_BEGIN = "<!-- qx:index:begin — generated by tools/perf_notebook.py; do not hand-edit -->"
INDEX_END = "<!-- qx:index:end -->"

DATE_LEAD_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*(?::|—|–|-)\s*(.*)$")
DATE_PAREN_RE = re.compile(r"^## (.*?)\s*\((\d{4}-\d{2}-\d{2})(?:[/\d-]*)\)\s*(.*)$")
CANON_DATE_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2}): (.+)$")


def parse_canonical(heading):
    """Parse `## YYYY-MM-DD: <title> — VERDICT[ detail]`.

    The verdict is anchored at the LAST ` — ` separator so titles containing
    em dashes parse correctly. Returns (date, title, verdict) or None.
    """
    m = CANON_DATE_RE.match(heading)
    if not m:
        return None
    parts = m.group(2).split(" — ")
    if len(parts) < 2:
        return None
    tail = parts[-1]
    token = tail.split()[0].strip("():,.") if tail.split() else ""
    if token not in KNOWN:
        return None
    return m.group(1), " — ".join(parts[:-1]), token

# ---------------------------------------------------------------------------
# Migration manifest: every undated H2 heading in a notebook must be listed
# here with a disposition, or migrate fails closed. Dispositions:
#   {"disposition": "attach-prev"}                  demote to H3, merge into
#                                                   the preceding block
#   {"disposition": "preamble"}                     move to the preamble
#                                                   (heading stays H2 only for
#                                                   PREAMBLE_HEADINGS titles;
#                                                   otherwise demoted to H3)
#   {"disposition": "date", "date": "YYYY-MM-DD",   become a dated entry;
#    "verdict": "RECORDED", "position": "first"}    position "first" sorts it
#                                                   before that date's entries
# "regions" declares stretches of the original file whose entries are in
# newest-first order; each region runs through the named heading (exact text).
# Blocks after the last region use "default_order".
# ---------------------------------------------------------------------------
MIGRATION_MANIFEST = {
    "gaudi": {
        "default_order": "oldest-first",
        "regions": [],
        "undated": {
            "## First Kernel Plan": {"disposition": "attach-prev"},
        },
    },
    "cuda": {
        "default_order": "oldest-first",
        "regions": [],
        "undated": {
            "## Current High-Leverage Backlog": {
                "disposition": "date", "date": "2026-07-06", "verdict": "RECORDED",
            },
            "## Open Questions": {"disposition": "attach-prev"},
            "## A100-vs-MI300X campaign": {
                "disposition": "date", "date": "2026-08-01", "verdict": "RECORDED",
            },
        },
        "verdict_overrides": {
            "## Campaign closed (2026-08-01)": "RECORDED",
        },
    },
    "rocm": {
        "default_order": "oldest-first",
        "regions": [],
        "undated": {
            "## Current Baseline Sources": {"disposition": "attach-prev"},
            "## Kernel Family Status": {"disposition": "attach-prev"},
            "## Open Questions": {"disposition": "attach-prev"},
        },
    },
    "xpu": {
        "default_order": "oldest-first",
        "regions": [],
        "undated": {
            "## First Kernel Plan": {"disposition": "attach-prev"},
        },
    },
    "metal": {
        "default_order": "oldest-first",
        # Two eras glued together: the top of the file is a newest-first log
        # ending at the Wave-6 close-out; everything after is oldest-first.
        # The bias orders same-date entries from different eras: the
        # oldest-first era's same-day entries come first.
        "regions": [
            {
                "order": "newest-first",
                "through": "## Wave-6 close-out (2026-07-02/03)",
                "bias": 1000000,
            },
        ],
        "undated": {
            "## Per-kernel log": {"disposition": "attach-prev"},
            "## Decision log": {"disposition": "attach-prev"},
            "## Baseline classification (2026-07-01, quick preset)": {
                "disposition": "date", "date": "2026-07-01", "verdict": "RECORDED",
            },
            "## Pass 2 (2026-07-01, commits e00a76d..): structural rewrites": {
                "disposition": "date", "date": "2026-07-01", "verdict": None,
            },
            "## Pass 3 (2026-07-01, mop-up): the five catalogued gaps": {
                "disposition": "date", "date": "2026-07-01", "verdict": None,
            },
            "## Wave-6 perf pass (2026-07-02, comprehensive sweep, 46 families / 536 cases / 0 skips)": {
                "disposition": "date", "date": "2026-07-02", "verdict": None,
            },
        },
    },
    "cpu": {
        "default_order": "oldest-first",
        # Newest-first era down through the 07-07 harness bring-up, then an
        # oldest-first tail of early 07-22 entries from the pre-flip era.
        "regions": [
            {
                "order": "newest-first",
                "through": "## 2026-07-07: Benchmark harness bring-up (system probes only)",
                "bias": 1000000,
            },
        ],
        "undated": {
            "## Required Entry Fields": {"disposition": "preamble"},
            "## Log": {
                "disposition": "date", "date": "2026-07-22",
                "verdict": "RECORDED", "position": "first",
            },
        },
    },
    # steady-state pseudo-backend used for the idempotency gate and `check`
    "_canonical": {"default_order": "oldest-first", "regions": [], "undated": {}},
}


def fail(msg):
    print(f"perf_notebook: {msg}", file=sys.stderr)
    sys.exit(2)


def strip_index(lines):
    """Remove a generated index block; return (lines, had_index, insert_at)."""
    out, i, had, insert_at = [], 0, False, None
    while i < len(lines):
        if lines[i].startswith("<!-- qx:index:begin"):
            if had:
                fail("multiple index blocks")
            had = True
            insert_at = len(out)
            while i < len(lines) and lines[i] != INDEX_END:
                i += 1
            if i == len(lines):
                fail("unterminated index block")
            i += 1
            # swallow at most one following blank line (we re-add it)
            if i < len(lines) and lines[i] == "":
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return out, had, insert_at


def split_blocks(lines):
    """Fence-aware split into (preamble_lines, [(heading, block_lines)])."""
    fence = False
    h2_at = []
    for idx, line in enumerate(lines):
        if line.lstrip().startswith("```"):
            fence = not fence
        elif not fence and line.startswith("## "):
            h2_at.append(idx)
    if fence:
        fail("unbalanced code fence at end of file")
    if not h2_at:
        return lines, []
    preamble = lines[: h2_at[0]]
    blocks = []
    for j, start in enumerate(h2_at):
        end = h2_at[j + 1] if j + 1 < len(h2_at) else len(lines)
        blocks.append([lines[start], lines[start + 1 : end]])
    # leading blocks whose titles are preamble furniture stay in the preamble
    while blocks and blocks[0][0][3:].strip() in PREAMBLE_HEADINGS:
        head, body = blocks.pop(0)
        preamble = preamble + [head] + body
    return preamble, blocks


def parse_heading(heading):
    """Return (date|None, title, verdict|None, canonical) for an H2 line."""
    c = parse_canonical(heading)
    if c:
        return c[0], c[1], c[2], True
    m = DATE_LEAD_RE.match(heading)
    if m:
        date, tail = m.group(1), m.group(2).strip()
        return date, tail, tail_verdict(tail), False
    m = DATE_PAREN_RE.match(heading)
    if m:
        title = (m.group(1) + (" " + m.group(3) if m.group(3) else "")).strip(" :—–-")
        return m.group(2), title, tail_verdict(title), False
    return None, heading[3:].strip(), None, False


def tail_verdict(text):
    """Detect a trailing ALL-CAPS verdict token after a dash, if recognized."""
    m = re.search(r"[—–-]\s*([A-Z][A-Z0-9_+/-]*)\b[^a-z]*$", text)
    if m and m.group(1) in KNOWN:
        return m.group(1)
    return None


def split_verdict_tail(text):
    """Split '<title> - VERDICT (extra)' into (title, 'VERDICT (extra)').

    Returns (text, None) when no recognized trailing verdict is present. The
    dash style before the verdict is normalized to an em dash by the caller;
    the verdict token and everything after it are preserved verbatim.
    """
    m = re.search(r"\s*[—–-]\s*([A-Z][A-Z0-9_+/-]*\b[^a-z]*)$", text)
    if m and m.group(1).split()[0].strip("():,.") in KNOWN:
        return text[: m.start()].rstrip(), m.group(1).rstrip()
    return text, None


def infer_verdict(body_lines):
    """Infer a verdict from entry body per the documented precedence."""
    decision = None
    for line in body_lines:
        s = line.strip().lstrip("-* ").strip()
        m = re.match(r"\**Decision\**\s*[:：]\s*(.*)", s, re.IGNORECASE)
        if m and decision is None:
            decision = m.group(1).lower()
    if decision:
        has_reject = bool(re.search(r"\breject", decision))
        has_keep = bool(re.search(r"\b(keep|kept|retain|adopt|land)", decision))
        has_defer = bool(re.search(r"\bdefer", decision))
        if has_reject and has_keep:
            return "MIXED"
        if has_reject:
            return "REJECTED"
        if has_keep:
            return "KEPT"
        if has_defer:
            return "DEFERRED"
    kept = rejected = False
    for line in body_lines:
        if re.match(r"^#{3,4} .*\bKept\b", line):
            kept = True
        if re.match(r"^#{3,4} .*\bRejected\b", line):
            rejected = True
    if kept and rejected:
        return "MIXED"
    if rejected:
        return "REJECTED"
    if kept:
        return "KEPT"
    for line in body_lines:
        s = line.strip().lstrip("-* ").strip()
        m = re.match(r"\**Status\**\s*[:：]\s*(\w+)", s, re.IGNORECASE)
        if m:
            tok = m.group(1).lower()
            if tok == "landed":
                return "LANDED"
            if tok == "deferred":
                return "DEFERRED"
            if tok == "candidate":
                return "CANDIDATE"
            if tok == "rejected":
                return "REJECTED"
    return "UNLABELED"


def assign_regions(blocks, manifest):
    """Tag each block index with its region (order, bias) per the manifest."""
    orders = []
    region_i = 0
    regions = manifest.get("regions", [])
    for head, _ in blocks:
        if region_i < len(regions):
            r = regions[region_i]
            orders.append((r["order"], r.get("bias", 0)))
            if head == r["through"]:
                region_i += 1
        else:
            orders.append((manifest.get("default_order", "oldest-first"), 0))
    return orders


def migrate_content(lines, manifest, backend, report):
    """Core transform. Returns (new_lines_without_index, entries_meta).

    entries_meta: list of (date, title, verdict, block_lines) in final order.
    report: dict collecting heading_map and transforms for printing/checks.
    """
    lines, _, _ = strip_index(lines)
    preamble, blocks = split_blocks(lines)

    # classify + fail closed on unknown undated headings
    undated_cfg = manifest.get("undated", {})
    unknown = []
    for head, _ in blocks:
        date, _, _, _ = parse_heading(head)
        if date is None and head not in undated_cfg:
            unknown.append(head)
    if unknown:
        fail(
            f"{backend}: undated headings not in MIGRATION_MANIFEST "
            f"(add dispositions):\n  " + "\n  ".join(unknown)
        )

    # fence-balance warning per block
    for head, body in blocks:
        toggles = sum(1 for l in [head] + body if l.lstrip().startswith("```"))
        if toggles % 2:
            report.setdefault("warnings", []).append(f"odd fence count in block: {head}")

    orders = assign_regions(blocks, manifest)

    # apply dispositions in file order
    merged = []  # [ {head, body, date, title, verdict, canonical, order, pos, first} ]
    transforms = report.setdefault("transforms", [])
    for i, (head, body) in enumerate(blocks):
        date, title, hverdict, canonical = parse_heading(head)
        if date is None:
            cfg = undated_cfg[head]
            disp = cfg["disposition"]
            if disp == "attach-prev":
                if not merged:
                    fail(f"{backend}: attach-prev with no preceding entry: {head}")
                demoted = "#" + head  # ## X -> ### X
                transforms.append((head, demoted))
                merged[-1]["body"] = merged[-1]["body"] + [demoted] + body
                continue
            if disp == "preamble":
                if head[3:].strip() in PREAMBLE_HEADINGS:
                    kept_head = head
                else:
                    kept_head = "#" + head
                    transforms.append((head, kept_head))
                preamble = preamble + [kept_head] + body
                continue
            if disp == "date":
                date = cfg["date"]
                hverdict = cfg.get("verdict", "RECORDED")
                canonical = False
            else:
                fail(f"{backend}: unknown disposition {disp!r} for {head}")
        first = False
        if head in undated_cfg and undated_cfg[head].get("position") == "first":
            first = True
        merged.append({
            "head": head, "body": body, "date": date, "title": title,
            "verdict": hverdict, "canonical": canonical,
            "order": orders[i], "pos": i, "first": first,
        })

    # verdict retrofit + new headings
    heading_map = report.setdefault("heading_map", [])
    overrides = manifest.get("verdict_overrides", {})
    for e in merged:
        if e["canonical"]:
            e["new_head"] = e["head"]
        else:
            title = e["title"].strip().rstrip(":").strip()
            bare_title, tail = split_verdict_tail(title)
            if e["head"] in overrides:
                verdict = overrides[e["head"]]
                e["new_head"] = f"## {e['date']}: {bare_title} — {verdict}"
            elif tail is not None:
                # verdict already in the heading; normalize the dash, keep the
                # token and any trailing detail verbatim
                e["new_head"] = f"## {e['date']}: {bare_title} — {tail}"
            else:
                verdict = e["verdict"] or infer_verdict(e["body"])
                e["new_head"] = f"## {e['date']}: {title} — {verdict}"
        if e["new_head"] != e["head"]:
            heading_map.append((e["head"], e["new_head"]))
            transforms.append((e["head"], e["new_head"]))
        c = parse_canonical(e["new_head"])
        if not c:
            fail(f"{backend}: constructed heading not canonical: {e['new_head']}")
        e["date"], e["title"], e["verdict"] = c

    # sort: (date, adj) with adj restoring intra-day order per region direction
    def key(e):
        if e["first"]:
            return (e["date"], float("-inf"))
        order, bias = e["order"]
        adj = bias + (-e["pos"] if order == "newest-first" else e["pos"])
        return (e["date"], adj)

    merged.sort(key=key)

    new_lines = list(preamble)
    for e in merged:
        new_lines.append(e["new_head"])
        new_lines.extend(e["body"])
    entries = [(e["date"], e["title"], e["verdict"], e) for e in merged]
    return new_lines, entries, len(preamble)


def build_index(entries_with_lines):
    rows = [INDEX_BEGIN, "### Index (generated)", "", "| date | entry | verdict | line |", "|---|---|---|---:|"]
    for date, title, verdict, line_no in entries_with_lines:
        safe_title = title.replace("|", "\\|")
        rows.append(f"| {date} | {safe_title} | {verdict} | {line_no} |")
    rows.append(INDEX_END)
    rows.append("")
    return rows


def insert_index(body_lines, entries, preamble_len):
    """Insert the index after the preamble; compute final line numbers."""
    index_len = 7 + len(entries)  # build_index rows for n entries
    final_entry_lines = []
    # entry heading offsets within body_lines
    offset = preamble_len
    metas = []
    for date, title, verdict, e in entries:
        # heading position: count from body start
        metas.append((date, title, verdict, e))
    # recompute by scanning body_lines after preamble
    positions = []
    for i in range(preamble_len, len(body_lines)):
        if body_lines[i].startswith("## "):
            positions.append(i)
    if len(positions) != len(entries):
        fail(f"internal: entry count mismatch ({len(positions)} headings vs {len(entries)} entries)")
    for (date, title, verdict, _), pos in zip(entries, positions):
        final_entry_lines.append((date, title, verdict, pos + index_len + 1))
    index_rows = build_index(final_entry_lines)
    if len(index_rows) != index_len:
        fail("internal: index height mismatch")
    return body_lines[:preamble_len] + index_rows + body_lines[preamble_len:]


def integrity_check(old_lines, new_lines_with_index, transforms, backend):
    old_stripped, _, _ = strip_index(old_lines)
    new_stripped, had_index, _ = strip_index(new_lines_with_index)
    if not had_index:
        fail(f"{backend}: migrated output lacks an index block")
    normalized_old = list(old_stripped)
    # apply transforms by exact line match, respecting multiplicity
    pending = Counter()
    for old, new in transforms:
        pending[(old, new)] += 1
    for (old, new), n in list(pending.items()):
        replaced = 0
        for i, line in enumerate(normalized_old):
            if line == old and replaced < n:
                normalized_old[i] = new
                replaced += 1
        if replaced != n:
            fail(f"{backend}: transform source line not found {old!r} (needed {n}, replaced {replaced})")
    ca, cb = Counter(normalized_old), Counter(new_stripped)
    if ca != cb:
        missing = ca - cb
        added = cb - ca
        detail = []
        for line, n in list(missing.items())[:5]:
            detail.append(f"  lost x{n}: {line!r}")
        for line, n in list(added.items())[:5]:
            detail.append(f"  gained x{n}: {line!r}")
        fail(f"{backend}: body-line multiset mismatch\n" + "\n".join(detail))


def cmd_migrate(args):
    path = Path(args.file)
    backend = args.backend
    if backend not in MIGRATION_MANIFEST:
        fail(f"unknown backend {backend!r}")
    manifest = MIGRATION_MANIFEST[backend]
    old_lines = path.read_text().splitlines()
    report = {}
    body, entries, preamble_len = migrate_content(list(old_lines), manifest, backend, report)
    final = insert_index(body, entries, preamble_len)
    integrity_check(old_lines, final, report.get("transforms", []), backend)

    # idempotency: canonical re-run must be a no-op
    report2 = {}
    body2, entries2, plen2 = migrate_content(list(final), MIGRATION_MANIFEST["_canonical"], backend, report2)
    final2 = insert_index(body2, entries2, plen2)
    if final2 != final:
        for a, b in zip(final, final2):
            if a != b:
                print(f"  first divergence:\n    pass1: {a!r}\n    pass2: {b!r}", file=sys.stderr)
                break
        fail(f"{backend}: migration is not idempotent")

    print(f"{backend}: {len(entries)} entries; {len(report.get('heading_map', []))} headings rewritten")
    for old, new in report.get("heading_map", []):
        print(f"  {old}\n    -> {new}")
    for w in report.get("warnings", []):
        print(f"  WARNING: {w}")
    if args.dry_run:
        print("dry-run: not writing")
        return 0
    path.write_text("\n".join(final) + "\n")
    print(f"wrote {path}")
    return 0


def canonical_pass(path):
    """Run the steady-state transform; returns (current_lines, expected_lines)."""
    old_lines = path.read_text().splitlines()
    report = {}
    body, entries, plen = migrate_content(
        list(old_lines), MIGRATION_MANIFEST["_canonical"], path.name, report
    )
    final = insert_index(body, entries, plen)
    return old_lines, final, entries


def cmd_index(args):
    path = Path(args.file)
    old_lines, final, _ = canonical_pass(path)
    if args.check:
        if old_lines != final:
            print(f"{path}: index or ordering stale")
            return 1
        print(f"{path}: index up to date")
        return 0
    path.write_text("\n".join(final) + "\n")
    print(f"{path}: index regenerated")
    return 0


def cmd_check(args):
    rc = 0
    for f in args.files:
        path = Path(f)
        problems = []
        lines = path.read_text().splitlines()
        stripped, had_index, _ = strip_index(list(lines))
        _, blocks = split_blocks(stripped)
        prev_date = None
        for head, _ in blocks:
            c = parse_canonical(head)
            if not c:
                problems.append(f"non-canonical heading: {head}")
                continue
            if prev_date is not None and c[0] < prev_date:
                problems.append(f"date order regression at: {head}")
            prev_date = c[0]
        if not had_index:
            problems.append("missing generated index block")
        elif not problems:
            old, expected, _ = canonical_pass(path)
            if old != expected:
                problems.append("index stale (run: perf_notebook.py index)")
        if problems:
            rc = 1
            print(f"{path}: FAIL")
            for p in problems:
                print(f"  {p}")
        else:
            print(f"{path}: ok")
    return rc


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    m = sub.add_parser("migrate")
    m.add_argument("file")
    m.add_argument("--backend", required=True)
    m.add_argument("--dry-run", action="store_true")
    m.set_defaults(func=cmd_migrate)
    i = sub.add_parser("index")
    i.add_argument("file")
    i.add_argument("--check", action="store_true")
    i.set_defaults(func=cmd_index)
    c = sub.add_parser("check")
    c.add_argument("files", nargs="+")
    c.set_defaults(func=cmd_check)
    args = ap.parse_args()
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
